hard_tabs = true
max_width = 120
fn_args_layout = "Compressed"
# rustup toolchain install nightly-x86_64-pc-windows-msvc
# cargo +nightly fmt
unstable_features = true
imports_granularity = "Crate"
overflow_delimited_expr = true
