hard_tabs = true
max_width = 120
fn_params_layout = "Compressed"
use_small_heuristics = "Max"
# rustup toolchain install nightly-x86_64-pc-windows-msvc
# cargo +nightly fmt
unstable_features = true
version = "Two"
imports_granularity = "Crate"
overflow_delimited_expr = true
